feat: add permission support
42signal/anyforce pull request #11
Opened 2023-05-12 06:53 UTC by zhongzi

2023-05-17 04:11 UTC, exherb reviewed
为什么不在业务那边做呢

2023-05-17 14:45 UTC, zhongzi commented
业务这边要怎么做？
两个功能：
1、资源操作权限控制
2、reset批量刷新，需要在提交之前清理非本次提交对象集合
😂

2023-05-18 01:32 UTC, exherb commented
https://github.com/adtalos/xapi/blob/master/python/xapi/api/base.py

这里控制

reset批量刷新是什么意思?

2023-05-18 01:33 UTC, exherb requested changes
block for accidentally merge

2023-05-18 02:00 UTC, zhongzi commented
在这里做的话，有合适的注入点吗？😂
还是没太明白。

2023-05-18 15:56 UTC, closed without merging