fix(CurrencyField): accept Sum result
42signal/anyforce pull request #9
Opened 2023-03-15 12:01 UTC by bloodynumen

2023-03-15 16:38 UTC, zhongzi approved these changes

2023-03-15 16:38 UTC, zhongzi commented on runtime/anyforce/model/fields.py
> +        if isinstance(value, Decimal):
BigInt sum之后会返回Decimal？
测试操作可以分享下不？😂

2023-03-16 02:11 UTC, bloodynumen commented on runtime/anyforce/model/fields.py
> +        if isinstance(value, Decimal):
```
    def group_by_f(
        self, group_by: str, field: Field[Any]
    ) -> Optional[Union[Function, Term]]:
        if group_by in [
            "bonus",
        ]:
            return Sum(group_by)
        return super().group_by_f(group_by, field)
```
bonus 是Currency Field

2023-03-16 02:12 UTC, bloodynumen commented on runtime/anyforce/model/fields.py
> +        if isinstance(value, Decimal):
可以看错误日志 会提示decimal/float 操作不支持

2023-03-20 10:25 UTC, exherb approved these changes

2023-03-20 10:26 UTC, exherb requested changes
其实可以直接 float()，不加这个判断

2023-03-21 03:49 UTC, exherb approved these changes

2023-03-21 03:49 UTC, merged